### ISSUE TITLE
Bug with two states with hours range as condition

### ISSUE THREAD

**Issue by SpaceMaster85** [petertufvesson/ha-fsm#1]
Hi,
thnak you for your amazing work! It works really great.
Unforutunatly I maybe found a bug :-(

I have two states "night" and "day". The transition is set as following:

      State(id='day', enter_programs=[self.day], transitions=[
        Transition(next='night', conditions=[
          Condition(hours=range(24,8))
        ])
      ]),
      State(id='night', enter_programs=[self.night], transitions=[
        Transition(next='day', conditions=[
          Condition(hours=range(8,24))
        ])
      ]) 

When the clock hits now 8, the states toggle between night and day.

2019-10-25 08:00:00.495071 INFO main_state_machine: main_state_machine_night_t0_c0 : Check timeout/state/stability/time = True/True/True/True = True
2019-10-25 08:00:00.517010 INFO main_state_machine: main_state_machine_night_t0 : Started in <main_state_machine_night> used <main_state_machine_night_t0> to get to <day>
2019-10-25 08:00:00.589829 WARNING main_state_machine: day
2019-10-25 08:00:00.596981 INFO main_state_machine: main_state_machine : Fsm state change (from hass) state=main_state_machine_day old=night new=day
2019-10-25 08:00:00.680450 INFO main_state_machine: main_state_machine_day_t0_c0 : Check timeout/state/stability/time = True/True/True/True = True
2019-10-25 08:00:00.695971 INFO main_state_machine: main_state_machine_day_t0 : Started in <main_state_machine_day> used <main_state_machine_day_t0> to get to <night>
2019-10-25 08:00:00.761264 INFO main_state_machine: main_state_machine : Fsm state change (from hass) state=main_state_machine_night old=day new=night
2019-10-25 08:00:00.768932 WARNING main_state_machine: night
2019-10-25 08:00:00.812860 INFO main_state_machine: main_state_machine_night_t0_c0 : Check timeout/state/stability/time = True/True/True/True = True
2019-10-25 08:00:00.842792 INFO main_state_machine: main_state_machine_night_t0 : Started in <main_state_machine_night> used <main_state_machine_night_t0> to get to <day>
2019-10-25 08:00:00.898028 INFO main_state_machine: main_state_machine : Fsm state change (from hass) state=main_state_machine_day old=night new=day
2019-10-25 08:00:00.915516 WARNING main_state_machine: day
2019-10-25 08:00:01.006402 INFO main_state_machine: main_state_machine_day_t0_c0 : Check timeout/state/stability/time = True/True/True/True = True
2019-10-25 08:00:01.019245 INFO main_state_machine: main_state_machine_day_t0 : Started in <main_state_machine_day> used <main_state_machine_day_t0> to get to <night>
2019-10-25 08:00:01.073469 INFO main_state_machine: main_state_machine : Fsm state change (from hass) state=main_state_machine_night old=day new=night
2019-10-25 08:00:01.082793 WARNING main_state_machine: night
2019-10-25 08:00:01.144445 INFO main_state_machine: main_state_machine_night_t0_c0 : Check timeout/state/stability/time = True/True/True/True = True
2019-10-25 08:00:01.169143 INFO main_state_machine: main_state_machine_night_t0 : Started in <main_state_machine_night> used <main_state_machine_night_t0> to get to <day>
2019-10-25 08:00:01.229521 INFO main_state_machine: main_state_machine : Fsm state change (from hass) state=main_state_machine_day old=night new=day
2019-10-25 08:00:01.244450 WARNING main_state_machine: day
2019-10-25 08:00:01.347007 INFO main_state_machine: main_state_machine_day_t0_c0 : Check timeout/state/stability/time = True/True/True/True = True
2019-10-25 08:00:01.362399 INFO main_state_machine: main_state_machine_day_t0 : Started in <main_state_machine_day> used <main_state_machine_day_t0> to get to <night>
2019-10-25 08:00:01.423048 INFO main_state_machine: main_state_machine : Fsm state change (from hass) state=main_state_machine_night old=day new=night
2019-10-25 08:00:01.438069 WARNING main_state_machine: night

**........ some hundred more times
This ends in** 

2019-10-25 08:00:39.362642 INFO main_state_machine: main_state_machine_night_t0 : Started in <main_state_machine_night> used <main_state_machine_night_t0> to get to <day>
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib/python3.7/traceback.py", line 121, in format_exception
    type(value), value, tb, limit=limit).format(chain=chain))
  File "/usr/lib/python3.7/traceback.py", line 497, in __init__
    _seen=_seen)
  File "/usr/lib/python3.7/traceback.py", line 497, in __init__
    _seen=_seen)
  File "/usr/lib/python3.7/traceback.py", line 497, in __init__
    _seen=_seen)
  [Previous line repeated 494 more times]
RecursionError: maximum recursion depth exceeded
2019-10-25 08:00:39.400841 WARNING AppDaemon: ------------------------------------------------------------
2019-10-25 08:00:39.401268 WARNING AppDaemon: Unexpected error in worker for App main_state_machine:
2019-10-25 08:00:39.401634 WARNING AppDaemon: Worker Ags: {'name': 'main_state_machine', 'id': UUID('5181a64a-2e48-41da-98bd-b8a8bfd4a297'), 'type': 'timer', 'function': <bound method Condition.time_callback of <fsm.Condition object at 0x7fb95dca2908>>, 'kwargs': {'interval': 3600}}
2019-10-25 08:00:39.401885 WARNING AppDaemon: ------------------------------------------------------------
Unhandled exception in thread started by <bound method Thread._bootstrap of <Thread(thread-3, started daemon 140434143181600)>>
Traceback (most recent call last):
  File "/config/appdaemon/apps/fsm.py", line 195, in enter
    self.fsm.change_state(self)
  File "/config/appdaemon/apps/fsm.py", line 94, in change_state
    self.hass.set_state(self.entity, state=self.state.name)
  File "/usr/lib/python3.7/site-packages/appdaemon/plugins/hass/hassapi.py", line 138, in set_state
    apiurl, headers=headers, json=new_state, verify=cert_path
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 157, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.7/socket.py", line 750, in getaddrinfo
    addrlist.append((_intenum_converter(af, AddressFamily),
  File "/usr/lib/python3.7/socket.py", line 103, in _intenum_converter
    return enum_klass(value)
  File "/usr/lib/python3.7/enum.py", line 310, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.7/enum.py", line 530, in __new__
    if type(value) is cls:
RecursionError: maximum recursion depth exceeded while calling a Python object

I think it is a problem with the hour check, but maybe you know how to fix it.

**Comment by SpaceMaster85** [comment]
I found the problem
  Condition(hours=range(24,8))
causes the problem:
It has to be
  Condition(hours=range(0,8))

**Comment by petertufvesson** [comment]
Yes, the range() command cannot be used like you do.

> len(range(24,8))
0
> len(range(8,24))
16

This means the state machine always go back to 'night', then back to 'day', and back again, in an eternal loop.
It is unfortunately quite easy to create these kinds of designs, and there is no safety net (yet) to detect them. Something to work on...!
